apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-stack-config-nemo-safety
data:
  run.yaml: |
    version: '2'
    image_name: nvidia
    
    apis:
      - agents
      - safety
      - inference
      - vector_io
      - tool_runtime
      - files
    
    providers:
      agents:
        - provider_id: meta-reference
          provider_type: inline::meta-reference
          config:
            persistence:
              agent_state:
                backend: kv_default
                namespace: agents
              responses:
                backend: sql_default
                table_name: responses
      
      inference:
        - provider_id: vllm
          provider_type: remote::vllm
          config:
            base_url: "${env.VLLM_URL}"
            api_token: "${env.VLLM_API_TOKEN}"
            network:
              tls:
                verify: false
      
      safety:
        - provider_id: nvidia-local-nemo
          provider_type: remote::nvidia
          config:
            guardrails_service_url: "${env.NEMO_GUARDRAILS_URL}"
            config_id: "${env.NEMO_CONFIG_ID}"
      
      vector_io:
        - provider_id: faiss
          provider_type: inline::faiss
          config:
            persistence:
              backend: kv_default
              namespace: vector_io::faiss
      
      tool_runtime:
        - provider_id: brave-search
          provider_type: remote::brave-search
          config: {}
      
      files:
        - provider_id: localfs
          provider_type: inline::localfs
          config:
            storage_dir: /.llama/files
            metadata_store:
              backend: sql_default
              table_name: files_metadata
    
    storage:
      backends:
        kv_default:
          type: kv_sqlite
          db_path: /.llama/kvstore.db
        sql_default:
          type: sql_sqlite
          db_path: /.llama/sql_store.db
        sql_inference:
          type: sql_sqlite
          db_path: /.llama/inference_store.db
      stores:
        metadata:
          namespace: registry
          backend: kv_default
        inference:
          table_name: inference_store
          backend: sql_inference
          max_write_queue_size: 10000
          num_writers: 4
        conversations:
          table_name: openai_conversations
          backend: sql_default
        responses:
          table_name: responses
          backend: sql_default
        prompts:
          namespace: prompts
          backend: kv_default
    
    registered_resources:
      models:
        - metadata: {}
          model_id: microsoft/phi-4
          provider_id: vllm
          provider_model_id: microsoft/phi-4
          model_type: llm
      shields:
        - shield_id: nemo-guardrail
          provider_id: nvidia-local-nemo
          provider_resource_id: nemo-model
      vector_dbs: []
      datasets: []
      scoring_fns: []
      benchmarks: []
      tool_groups: []
---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: lls-nemo
spec:
  replicas: 1
  network:
    allowedFrom:
      namespaces:
        - "*"  
  server:
    distribution:
      image: quay.io/rh-ee-mmisiura/lls@sha256:b3e1f672e06c2c18bebe292a534b5383f5c2ad39a9e5915d39f68456002930a6
    containerSpec:
      env:
        - name: MILVUS_DB_PATH
          value: "/.llama/milvus.db"
        - name: VLLM_URL
          valueFrom:
            secretKeyRef:
              name: llama-stack-credentials
              key: vllm-url
        - name: VLLM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-credentials
              key: vllm-api-token
        - name: NEMO_GUARDRAILS_URL
          valueFrom:
            secretKeyRef:
              name: llama-stack-credentials
              key: nemo-guardrails-url
        - name: NEMO_CONFIG_ID
          valueFrom:
            secretKeyRef:
              name: llama-stack-credentials
              key: nemo-config-id
      name: llama-stack
      port: 8321
    userConfig:
      configMapName: llama-stack-config-nemo-safety
    storage:
      size: 20Gi
      mountPath: /.llama
