apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-credentials
type: Opaque
stringData:
  vllm-url: "INSERT ME"
  vllm-api-token: "INSERT ME"
  nemo-guardrails-url: "INSERT ME"
  nemo-config-id: "INSERT ME"