apiVersion: v1
kind: ConfigMap
metadata:
  name: config-plain-model
data:
  config.yaml: |
      models:
        - type: main
          engine: openai
          parameters:
            openai_api_base: ${LLM_API_BASE}
            model_name: ${LLM_MODEL_NAME}
            api_key: ${LLM_API_KEY}

    instructions:
      - type: general
        content: |
          You are a helpful assistant specialized exclusively in lemons.
          Respond only with information that is directly about lemons or lemon-related topics.
          If the user request is not about lemons, kindly refuse.
          Answer in a maximum of 10 sentences.
