---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: prompt-injection-detector-runtime
  annotations:
    openshift.io/display-name: Prompt Injection Detector ServingRuntime
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  labels:
    opendatahub.io/dashboard: "true"
spec:
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: huggingface
  containers:
    - name: kserve-container
      image: quay.io/rh-ee-mmisiura/kserve/huggingfaceserver:latest-gpu
      args:
        - --model_name=prompt-injection-detector
        - --return_probabilities
        - --backend=huggingface
        - --dtype=float32
      ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: prompt-injection-detector
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    serving.kserve.io/deploymentMode: RawDeployment
    security.opendatahub.io/enable-auth: "false"
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --task=sequence_classification
      runtime: prompt-injection-detector-runtime
      storageUri: hf://protectai/deberta-v3-base-prompt-injection
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "1"
        memory: 2Gi
        nvidia.com/gpu: "1"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prompt-injection-detector-route
  labels:
    app: prompt-injection-detector
spec:
  to:
    kind: Service
    name: prompt-injection-detector-predictor
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
