apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: lls-fms
spec:
  replicas: 1
  server:
    containerSpec:
      env:
        - name: VLLM_URL
          value: ${VLLM_URL}
        - name: INFERENCE_MODEL
          value: ${INFERENCE_MODEL}
        - name: VLLM_API_TOKEN
          value: ${VLLM_API_TOKEN}
        - name: VLLM_TLS_VERIFY
          value: "false"
        - name: MILVUS_DB_PATH
          value: ~/.llama/milvus.db
        - name: FMS_ORCHESTRATOR_URL
          value: "${FMS_ORCHESTRATOR_URL}"
      name: llama-stack
      port: 8321
    distribution:
      image: quay.io/rh-ee-mmisiura/lls:fms_oauth
      imagePullPolicy: Always
    storage:
      size: 20Gi