kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-nlp
data:
  config.yaml: |
    detectors:
      built-in-detector:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      ibm-hap-38m-detector:
        type: text_contents
        service:
            hostname: "ibm-hap-38m-detector-predictor.testing.svc.cluster.local"
            port: 8443
            tls: ibm-hap-38m-tls
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
    tls:
      ibm-hap-38m-tls:
        cert_path: "/etc/tls/ibm-hap-38m/tls.crt"
        key_path: "/etc/tls/ibm-hap-38m/tls.key"
        client_ca_cert_path: "/etc/tls/ca/service-ca.crt"
    passthrough_headers:
      - Authorization
      - Content-Type
      - x-forwarded-access-token
    rewrite_forwarded_access_header: true
---
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
  annotations:
    security.opendatahub.io/enable-auth: 'true' 
spec:
  orchestratorConfig: "fms-orchestr8-config-nlp"
  enableBuiltInDetectors: true
  enableGuardrailsGateway: false
  replicas: 1
---
