apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama-prompt-guard-2-86m-detector
  labels:
    opendatahub.io/dashboard: 'true'
    trustyai/guardrails: 'true'
  annotations:
    openshift.io/display-name: llama-prompt-guard-2-86m-detector
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
    security.opendatahub.io/enable-auth: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    model:
      modelFormat:
        name: guardrails-detector-huggingface
      name: ''
      runtime: guardrails-detector-runtime-llama-prompt-guard-2-86m
      storage:
        key: aws-connection-minio-data-connection-detector-models
        path: Llama-Prompt-Guard-2-86M
      resources:
        limits:
          cpu: '1'
          memory: 6Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '500m'
          memory: 4Gi
          nvidia.com/gpu: '1'
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llama-prompt-guard-2-86m-detector-route
spec:
  to:
    kind: Service
    name: llama-prompt-guard-2-86m-detector-predictor
  port:
    targetPort: https
  tls:
    termination: reencrypt