apiVersion: v1
kind: Secret
metadata:
  name: api
type: Opaque
stringData:
  openai-api-key: "${OPENAI_API_KEY}"
  model-base-url: "${MAIN_MODEL_BASE_URL}"
  model-name: "${MODEL_NAME}"
  model-engine: "${MAIN_MODEL_ENGINE}"
  tempo-endpoint: "${TEMPO_ENDPOINT}"
