apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: hf-classifier-test
  annotations:
    security.opendatahub.io/enable-auth: 'true'
spec:
  nemoConfigs:
    - name: hf-classifier-test
      default: true
      configMaps:
        - hf-classifier-config
  env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: hf-classifier-llm
          key: api-key
    - name: OC_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-classifier-llm
          key: oc-token
