apiVersion: apps/v1
kind: Deployment
metadata:
  name: topic-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topic-detector
  template:
    metadata:
      labels:
        app: topic-detector
    spec:
      containers:
        - name: detector
          image: quay.io/rh-ee-mmisiura/regex-detector:custom_embed_detector
          ports:
            - containerPort: 8080
          env:
            - name: TOPIC_CONFIG_PATH
              value: "/config/topics.yaml"
          volumeMounts:
            - name: topic-config
              mountPath: /config
              readOnly: true
            - name: embedding-token
              mountPath: /secrets/embedding-token
              readOnly: true
      volumes:
        - name: topic-config
          configMap:
            name: topic-detector-config
        - name: embedding-token
          secret:
            secretName: embedding-service-token
            optional: true  
---
apiVersion: v1
kind: Service
metadata:
  name: topic-detector
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: topic-detector
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: topic-detector
spec:
  to:
    kind: Service
    name: topic-detector
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
