---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: embedding-detector-runtime
  annotations:
    openshift.io/display-name: embedding Detector ServingRuntime
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  labels:
    opendatahub.io/dashboard: "true"
spec:
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: huggingface
  containers:
    - name: kserve-container
      image: quay.io/rh-ee-mmisiura/kserve/huggingfaceserver:latest-gpu
      args:
        - --model_name=embedding-detector
        - --model_id=sentence-transformers/all-MiniLM-L6-v2
        - --return_probabilities
        - --backend=huggingface
      ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: embedding-detector
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    serving.kserve.io/deploymentMode: RawDeployment
    security.opendatahub.io/enable-auth: "true"
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --task=text_embedding
      runtime: embedding-detector-runtime
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "1"
        memory: 2Gi
        nvidia.com/gpu: "1"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: embedding-detector-route
  labels:
    app: embedding-detector
spec:
  to:
    kind: Service
    name: embedding-detector-predictor
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
