---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nemo-models-pvc
  labels:
    app: nemo-guardrails
    component: models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp3-csi
