apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-classifier-runtime
  annotations:
    openshift.io/display-name: vLLM Classifier ServingRuntime for KServe
    opendatahub.io/template-display-name: vLLM Classifier ServingRuntime for KServe
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    openshift.io/display-name: vLLM Classifier ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: 'true'
  containers:
    - command:
        - sh
        - '-c'
        - |
          echo "default:x:$(id -u):0:default:/tmp:/bin/sh" >> /etc/passwd
          exec vllm serve /mnt/models --port=8080 --served-model-name={{.Name}} --runner=pooling --dtype=float16 --max-model-len=512 --enforce-eager
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: HOME
          value: /tmp
      image: 'vllm/vllm-openai:latest'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: language-classifier
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: language-classifier
    security.opendatahub.io/enable-auth: 'true'
    security.opendatahub.io/auth-proxy-type: kube-rbac-proxy
    serving.knative.openshift.io/enablePassthrough: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: vllm-classifier-runtime
      storageUri: hf://papluca/xlm-roberta-base-language-detection
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: language-classifier-route
spec:
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: language-classifier-predictor
