---
apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-trustyai-credentials
type: Opaque
stringData:
  fms-orchestrator-url: "https://INSERT_ME"
  token: "INSERT_ME"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-stack-config-trustyai
data:
  config.yaml: |
    version: '2'
    image_name: trial
    
    apis:
      - safety
      - shields
    
    registered_resources:
      shields:
        - shield_id: secure_shield
          provider_id: trustyai_fms
    
    providers:
      safety:
        - provider_id: trustyai_fms
          provider_type: remote::trustyai_fms
          module: llama_stack_provider_trustyai_fms
          config:
            orchestrator_url: ${env.FMS_ORCHESTRATOR_URL}
            auth_token: ${env.TOKEN}
            verify_ssl: true
            shields:
              secure_shield:
                type: content
                confidence_threshold: 0.5
                message_types:
                  - user
                  - system
                detectors:
                  ibm-hap-38m-detector:
                    detector_params: {}
                  built-in-detector:
                    detector_params:
                      regex:
                        - email
                        - ^hello$
    
    storage:
      backends:
        kv_default:
          type: kv_sqlite
          db_path: /.llama/llama-stack-kv.db
        sql_default:
          type: sql_sqlite
          db_path: /.llama/llama-stack-sql.db
      stores:
        metadata:
          backend: kv_default
          namespace: trustyai_metadata
        prompts:
          backend: kv_default
          namespace: trustyai_prompts
        conversations:
          backend: sql_default
          table_name: conversations
        responses:
          backend: sql_default
          table_name: responses
        inference:
          backend: sql_default
          table_name: inference
---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: lls-trustyai
spec:
  replicas: 1
  network:
    allowedFrom:
      namespaces:
        - "*"
  server:
    distribution:
      image: quay.io/opendatahub/llama-stack:odh-pr-linux-x86-64
    containerSpec:
      env:
        - name: FMS_ORCHESTRATOR_URL
          valueFrom:
            secretKeyRef:
              name: llama-stack-trustyai-credentials
              key: fms-orchestrator-url
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-trustyai-credentials
              key: token
      name: llama-stack
      port: 8321
    userConfig:
      configMapName: llama-stack-config-trustyai
      configMapKey: config.yaml
    storage:
      size: 5Gi
      mountPath: /.llama

