---
apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-trustyai-credentials
type: Opaque
stringData:
  fms-orchestrator-url: "https://INSERT_ME"
  token: "INSERT_ME"
  vllm-url: "https:/INSERT_ME/v"
  vllm-api-token: "INSERT_ME"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-stack-config-trustyai
data:
  config.yaml: |
    version: '2'
    image_name: trial
    
    apis:
      - agents
      - safety
      - inference
      - vector_io
      - tool_runtime
      - files
    
    registered_resources:
      shields:
        - shield_id: secure_shield
          provider_id: trustyai_fms
      models:
        - metadata: {}
          model_id: microsoft/phi-4
          provider_id: vllm
          provider_model_id: microsoft/phi-4
          model_type: llm
      vector_dbs: []
      datasets: []
      scoring_fns: []
      benchmarks: []
      tool_groups: []
    
    providers:
      agents:
        - provider_id: meta-reference
          provider_type: inline::meta-reference
          config:
            persistence:
              agent_state:
                backend: kv_default
                namespace: agents
              responses:
                backend: sql_default
                table_name: responses
      
      safety:
        - provider_id: trustyai_fms
          provider_type: remote::trustyai_fms
          module: llama_stack_provider_trustyai_fms
          config:
            orchestrator_url: ${env.FMS_ORCHESTRATOR_URL}
            auth_token: ${env.TOKEN}
            verify_ssl: true
            shields:
              secure_shield:
                type: content
                confidence_threshold: 0.5
                message_types:
                  - user
                  - system
                detectors:
                  ibm-hap-38m-detector:
                    detector_params: {}
                  built-in-detector:
                    detector_params:
                      regex:
                        - email
                        - ^hello$
      
      inference:
        - provider_id: vllm
          provider_type: remote::vllm
          config:
            base_url: ${env.VLLM_URL}
            api_token: ${env.VLLM_API_TOKEN}
            network:
              tls:
                verify: false
      
      vector_io:
        - provider_id: faiss
          provider_type: inline::faiss
          config:
            persistence:
              backend: kv_default
              namespace: vector_io::faiss
      
      tool_runtime:
        - provider_id: brave-search
          provider_type: remote::brave-search
          config: {}
      
      files:
        - provider_id: localfs
          provider_type: inline::localfs
          config:
            storage_dir: /.llama/files
            metadata_store:
              backend: sql_default
              table_name: files_metadata
    
    storage:
      backends:
        kv_default:
          type: kv_sqlite
          db_path: /.llama/kvstore.db
        sql_default:
          type: sql_sqlite
          db_path: /.llama/sql_store.db
        sql_inference:
          type: sql_sqlite
          db_path: /.llama/inference_store.db
      stores:
        metadata:
          namespace: registry
          backend: kv_default
        inference:
          table_name: inference_store
          backend: sql_inference
          max_write_queue_size: 10000
          num_writers: 4
        conversations:
          table_name: openai_conversations
          backend: sql_default
        responses:
          table_name: responses
          backend: sql_default
        prompts:
          namespace: prompts
          backend: kv_default
---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: lls-trustyai
spec:
  replicas: 1
  network:
    allowedFrom:
      namespaces:
        - "*"
  server:
    distribution:
      image: quay.io/opendatahub/llama-stack:odh-pr-linux-x86-64
    containerSpec:
      env:
        - name: FMS_ORCHESTRATOR_URL
          valueFrom:
            secretKeyRef:
              name: llama-stack-trustyai-credentials
              key: fms-orchestrator-url
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-trustyai-credentials
              key: token
        - name: VLLM_URL
          valueFrom:
            secretKeyRef:
              name: llama-stack-trustyai-credentials
              key: vllm-url
        - name: VLLM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-trustyai-credentials
              key: vllm-api-token
        - name: MILVUS_DB_PATH
          value: "/.llama/milvus.db"
      name: llama-stack
      port: 8321
    userConfig:
      configMapName: llama-stack-config-trustyai
      configMapKey: config.yaml
    storage:
      size: 20Gi
      mountPath: /.llama
