apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: nemo
  annotations:
    security.opendatahub.io/enable-auth: 'true'
spec:
  nemoConfigs:
    - name: pii-plus-self-check
      default: true
      configMaps:
        - api-config
  env:
    - name: CONFIG_ID
      value: pii-plus-self-check
    - name: MAIN_MODEL_ENGINE
      valueFrom:
        secretKeyRef:
          name: api
          key: model-engine
    - name: MAIN_MODEL_BASE_URL
      valueFrom:
        secretKeyRef:
          name: api
          key: model-base-url
    - name: MODEL_NAME
      valueFrom:
        secretKeyRef:
          name: api
          key: model-name
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: api
          key: openai-api-key
