kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-nlp
data:
  config.yaml: |
    detectors:
      regex:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
---
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
  annotations:
    security.opendatahub.io/enable-auth: 'true' 
spec:
  orchestratorConfig: "fms-orchestr8-config-nlp"
  guardrailsGatewayConfig: "guardrails-orchestrator-sidecar-gateway-config"
  enableBuiltInDetectors: true
  enableGuardrailsGateway: true
  replicas: 1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: guardrails-orchestrator-sidecar-gateway-config 
  labels:
    app: fmstack-nlp
data:
  config.yaml: |
    orchestrator:
      host: "localhost"
      port: 8032
    detectors:
      - name: regex
        input: true
        output: true
        detector_params:
          regex:
            - \b(?i:email)\b
    routes:
      - name: all
        detectors:
          - regex
      - name: passthrough
        detectors:
---
